# Generated by Django 4.2.7 on 2025-09-06 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_type', models.CharField(max_length=30, unique=True)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('default_priority', models.CharField(default='MEDIUM', max_length=10)),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modèle de notification',
                'verbose_name_plural': 'Modèles de notifications',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_schedule_changes', models.BooleanField(default=True)),
                ('email_cancellations', models.BooleanField(default=True)),
                ('email_makeups', models.BooleanField(default=True)),
                ('email_conflicts', models.BooleanField(default=False)),
                ('sms_urgent_only', models.BooleanField(default=True)),
                ('sms_cancellations', models.BooleanField(default=False)),
                ('push_all', models.BooleanField(default=True)),
                ('push_schedule_changes', models.BooleanField(default=True)),
                ('push_reminders', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.PositiveIntegerField(default=30)),
                ('quiet_hours_start', models.TimeField(default='22:00')),
                ('quiet_hours_end', models.TimeField(default='08:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences de notification',
                'verbose_name_plural': 'Préférences de notifications',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_type', models.CharField(choices=[('SCHEDULE_CREATED', 'Emploi du temps créé'), ('SCHEDULE_UPDATED', 'Emploi du temps modifié'), ('SCHEDULE_CANCELLED', 'Cours annulé'), ('MAKEUP_REQUESTED', 'Rattrapage demandé'), ('MAKEUP_APPROVED', 'Rattrapage approuvé'), ('MAKEUP_REJECTED', 'Rattrapage rejeté'), ('CONFLICT_DETECTED', 'Conflit détecté'), ('ROOM_CHANGED', 'Changement de salle'), ('TEACHER_UNAVAILABLE', 'Enseignant indisponible'), ('SYSTEM_MAINTENANCE', 'Maintenance système')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_email', models.BooleanField(default=False)),
                ('sent_sms', models.BooleanField(default=False)),
                ('sent_push', models.BooleanField(default=False)),
                ('makeup_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduling.makeupsession')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduling.schedule')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
